<a href="https://colab.research.google.com/github/karthi234231/FML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=np.array([[1,2,3],[6,7,8]],dtype='int16')
print("shape:",b.shape)
print("dimension:",b.ndim)
print("datatype:",a.dtype)
print("datatype:",b.dtype)
print("itemsize:",a.itemsize)
print(a.size,b.size)
print("Size of the array: ",a.size)
 
print("Memory size of one array element in bytes: ",a.itemsize)

shape: (2, 3)
dimension: 2
datatype: int64
datatype: int16
itemsize: 8
14 6
Size of the array:  14
Memory size of one array element in bytes:  8


In [ ]:
#slicing
a1=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1[0,4])
print(a1[1,:])
print(a1[0,2:5])
print(a1[1,0:8:2])
print(a1[:,2])

5
[ 8  9 10 11 12 13 14]
[3 4 5]
[ 8 10 12 14]
[ 3 10]


In [ ]:
import numpy as np

a2=np.zeros((3,4))
a3=np.zeros(5,int)
print(a2)
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 0 0 0 0]


In [ ]:
b1=np.full((2,2),99)
print(b1)

[[99 99]
 [99 99]]


In [ ]:
b2=np.identity(3,int)
b3=np.eye(3,dtype='int')
print(b2)
print(b3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
arr1=np.random.rand(4,2)
arr2=np.random.randint(0,[10,3,4])
arr3=np.random.randint([9,3,4],10)
print(arr2)
print("")
print(arr1)
print("")
print(arr3)


[8 0 1]

[[0.26188326 0.0853826 ]
 [0.13616493 0.74316114]
 [0.59121447 0.72415622]
 [0.11597491 0.94675093]]

[9 4 5]


In [ ]:
ar1=np.array([1,2,3,4])
print(np.sum(ar1))
print(np.max(ar1))
print(np.min(ar1))

10
4
1


In [ ]:
n1=np.array([[1,2,3,4],[2,3,4,5]])
n2=np.array([[2,3,4,5],[3,3,2,1]])
print(n1*n2)
print("  ")
cross=np.cross(n1,)

[[ 2  6 12 20]
 [ 6  9  8  5]]
  
